# Generated by Django 5.2.7 on 2025-10-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('sla_minutes', models.IntegerField(default=60)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority_score', models.FloatField(default=0.0)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'priority_score'], name='ops_process_status_c0e2cd_idx')],
            },
        ),
    ]
