services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  db_data: